### PR TITLE
Update dependencies - Test-Frame, Log4j, Slf4j, helm-client

### PR DESCRIPTION
**Pull request by im-konge**
This PR updates few dependencies - I wanted to update the `test-frame`, in order to implement the LogCollector, but during that, I had to update also the Log4j and Slf4j deps. Finally, the helm-client dependency has a new version as well, so I updated it all together.

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
So, is the operator / JOSDK using SLF4J2? Because I'm not sure it can be updated from 1 to 2 just like that.

**Comment by im-konge** [comment]
So based on this: https://github.com/operator-framework/java-operator-sdk/blob/main/pom.xml#L168 no.
The build of the operator was fine, but I will build the image and check if it will break something in the logging during the STs.

**Comment by im-konge** [comment]
But I will try to use the new version just in STs, I think that should be possible.

**Comment by im-konge** [comment]
@scholzj I changed the SLF4J to SLF4J2 just in the STs, so it should not break anything. But I will anyway build the image and verify that I didn't break anything with this change.

**Comment by im-konge** [comment]
So I built the image and it seems that everything works fine:
```
2024-11-22 11:06:14 INFO  KafkaAccessOperator:28 - Kafka Access operator starting
2024-11-22 11:06:15 WARN  Default ConfigurationService implementation:61 - Configuration for reconciler 'kafkaaccessreconciler' was not found. Known reconcilers: None.
2024-11-22 11:06:15 INFO  Default ConfigurationService implementation:83 - Created configuration for reconciler io.strimzi.kafka.access.KafkaAccessReconciler with name kafkaaccessreconciler
2024-11-22 11:06:15 INFO  KafkaAccessOperator:150 - Preparing event sources
2024-11-22 11:06:15 INFO  KafkaAccessOperator:188 - Finished preparing event sources
2024-11-22 11:06:15 INFO  Operator:243 - Registered reconciler: 'kafkaaccessreconciler' for resource: 'class io.strimzi.kafka.access.model.KafkaAccess' for namespace(s): [all namespaces]
2024-11-22 11:06:15 INFO  Operator:147 - Operator SDK 4.4.2 (commit: 8234e84) built on 2023-08-16T06:00:51.000+0000 starting...
2024-11-22 11:06:15 INFO  Operator:153 - Client version: 6.13.4
2024-11-22 11:06:15 INFO  Controller:334 - Starting 'kafkaaccessreconciler' controller for reconciler: io.strimzi.kafka.access.KafkaAccessReconciler, resource: io.strimzi.kafka.access.model.KafkaAccess
2024-11-22 11:06:15 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkaaccesses' with unstable version 'v1alpha1'
2024-11-22 11:06:16 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkas' with unstable version 'v1beta2'
2024-11-22 11:06:16 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkausers' with unstable version 'v1beta2'
2024-11-22 11:06:17 INFO  Controller:346 - 'kafkaaccessreconciler' controller started
2024-11-22 11:06:17 INFO  Server:384 - jetty-11.0.24; built: 2024-08-26T18:11:22.448Z; git: 5dfc59a691b748796f922208956bd1f2794bcd16; jvm 17.0.13+11-LTS
2024-11-22 11:06:17 INFO  AbstractConnector:376 - Started ServerConnector@4e4efc1b{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2024-11-22 11:06:17 INFO  Server:439 - Started Server@4108fa66{STARTING}[11.0.24,sto=0] @4473ms
2024-11-22 11:06:17 INFO  KafkaAccessOperator:39 - Kafka Access operator is now ready (health server listening)
```

**Review by scholzj — APPROVED** [review]

**Review by katheris — APPROVED** [review]
LGTM thanks

**Pull request merged**
