### PR TITLE
Add Dockerfile and make and Azure steps to build it

### PR DESCRIPTION
**Pull request by katheris**
* Add Dockerfile, run_java.sh and make files to build the docker image.
* Update Azure pipeline to build Docker container.
* Add DEV_GUIDE.md with steps for building the Docker image.

This PR does not include the steps to tag and push the docker image. Those will be added with the deployment files in a followup PR.

This PR only builds the amd64 architecture.

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I think this looks good to me. The only thing I wonder about is whether we really need to have the folder `docker-images` => I assume it will be just one image, so maybe the plural is not needed?

**Comment by katheris** [comment]
@scholzj that's a good point, I'll update it. At the moment the azure builds are configured to build the Java project and image but not try to push images anywhere, but they don't seem to run when a PR is raised. Does this need to be enabled from the repo settings?

**Comment by scholzj** [comment]
@katheris You have a wrong path there: `templates/jobs/build/build_container.yaml` instead of `templates/jobs/build_container.yaml`?

**Comment by katheris** [comment]
@scholzj ah ok, I'll sort that. How do I get from the PR to the azure build? I was expecting it to come up under the checks

**Comment by katheris** [comment]
@scholzj the Azure build is passing now

**Comment by scholzj** [comment]
> How do I get from the PR to the azure build? I was expecting it to come up under the checks

When you have misconfiguration in the build like this, it does nto even start the build, so it does not report the error on the PR. You have to browse the builds to find it.

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Pull request merged**
